package com.cab302thursdaytbd.Service;

import org.json.JSONObject;

import java.io.IOException;
import java.net.URI;
import java.net.http.HttpClient;
import java.net.http.HttpRequest;
import java.net.http.HttpResponse;

/**
 *Class responsible for communicating with gemini API
 * Retrieves AI generated responses for the pet.
 * Sends User prompt sent from pet controller to here then enters them into the api.
 */
public class PetConversationService {
    /**
     * Shows what model AI we are using and shows the use of an enviornment variable instead.
     * This is safer and we don't have to upload the APIKey to GitHub
     */
    private final String apiKey;
    private static final String url = "https://generativelanguage.googleapis.com/v1beta/models/gemini-3-flash-preview:generateContent";

    /**
     * Contructs a PetConversationService and gets the apiKey
     */
    public PetConversationService() {
        this.apiKey = System.getenv("DesktopPetAPIKey");
    }

    /**
     * Sends a prompt to gemini and returns a response that it has generated
     * The prompt is in JSON form where we use JSONObject Library to get the Text from that JSON and returned the response to the caller.
     * This is a mix of 2 different templates started out as a ChatGPT template but was changed with switching to GeminiAPI and their given templates for APIs.
     * @param question the prompt that goes to Gemini.
     * @return the text generated by Gemini.
     * @throws IOException if an error happens while responding.
     * @throws InterruptedException if the HTTP request has problems.
     */
    public String askQuestion(String question) throws IOException, InterruptedException {
        String jsonBody = "{" +
                "\"contents\": [{" +
                "\"parts\":[{" +
                "\"text\": \"" + question + "\"" +
                "}]" +
                "}]" +
                "}";
        HttpRequest request = HttpRequest.newBuilder()
                .uri(URI.create(PetConversationService.url))
                .header("Content-Type", "application/json")
                // Gemini uses 'x-goog-api-key' instead of 'Authorization: Bearer'
                .header("x-goog-api-key", apiKey)
                .POST(HttpRequest.BodyPublishers.ofString(jsonBody))
                .build();

        HttpClient client = HttpClient.newHttpClient();
        String respText = null;
        try {
            HttpResponse<String> response = client.send(request, HttpResponse.BodyHandlers.ofString());
            int statusCode = response.statusCode();
            String strJsonResBody = response.body();
            System.out.println("Status Code: " + statusCode);
            if (statusCode == 200) {
                System.out.println("Response: " + strJsonResBody);
                JSONObject jsonResp = new JSONObject(strJsonResBody);
                respText = jsonResp.getJSONArray("candidates").getJSONObject(0).getJSONObject("content").getJSONArray("parts").getJSONObject(0).getString("text");
            }
        } catch (Exception e) {
            System.err.println("Error calling Gemini: " + e.getMessage());
            throw e;
        }
        return respText;
    }
}
