package com.cab302thursdaytbd;

import com.cab302thursdaytbd.Model.Pet;
import com.cab302thursdaytbd.Model.PetDAO;
import com.cab302thursdaytbd.Model.Session;
import com.cab302thursdaytbd.Service.PetConversationService;
import javafx.event.ActionEvent;
import javafx.fxml.FXML;
import javafx.fxml.FXMLLoader;
import javafx.scene.Node;
import javafx.scene.Parent;
import javafx.scene.control.Button;
import javafx.scene.control.TextArea;
import javafx.scene.control.TextField;
import javafx.stage.Stage;
import java.io.IOException;
import java.util.Objects;

/**
 * Controller for the conversation_page.fxml
 * Handles all user interactions and interacts with the API for the AI pet service.
 * Displays Responses onto the TextField in the conversation page.
 *
 * Aiden Coorey
 */
public class PetConversationController {
    private final PetDAO petDAO = new PetDAO();
    public Button sendButton;
    @FXML
    private TextArea chatTextArea;

    @FXML
    private TextField messageField;

    private PetConversationService petService;
    int userId;

    /**
     * Initializes the controller.
     * Gets the current users ID so we know who's using the application this session
     *Makes the ChatBox unable to be edited by the user.
     */
    @FXML
    public void initialize() {
        chatTextArea.setEditable(false);
        userId = Session.getUserId();
        petService = new PetConversationService();
    }

    /**
     * Handles the back button action.
     * If clicked sends them back to the main page.
     *
     * @param event the action generated by clicking the back button
     * @throws IOException if the main page cannot be loaded.
     */
    @FXML
    private void handleBackButtonAction(ActionEvent event) throws IOException {
        Parent newRoot = FXMLLoader.load(Objects.requireNonNull(getClass().getResource("main_page.fxml")));
        Stage stage = (Stage)((Node)event.getSource()).getScene().getWindow();
        stage.getScene().setRoot(newRoot);
        stage.show();
        stage.setResizable(false);

    }

    /**
     * Handles Send button Actions
     * Responsible for sending the users message to the API and receiving a response.
     * appends those responses onto the text area.
     * Pauses the send button after each request until the API has returned a response to prevent spam.
     * Conversation request is done on a seperate thread with runnable.
     */
    @FXML
    private void handleSendButtonAction() {

        Runnable handleSend = () -> {

            sendButton.setDisable(true);
            Pet pet = petDAO.getPet(userId);

            String prompt = messageField.getText();
            String aiPrompt = "In this the energy level, hunger 10 being fully fed, affection and boredom have a scale from 1 - 10. You should reply as if you are a " + pet.getPetType() + " with the name " + pet.getPetName() + " do not reply with actions, that current has a energy level of " + pet.getEnergy() + " a boredom scale of " + pet.getBoredom() + " a hunger level of " + pet.getHunger() + " and a affection level of " + pet.getAffection() + prompt;
            chatTextArea.appendText("*" + Session.getUsername() + "*\n" + prompt + "\n\n");

            String response;
            try {

                response = petService.askQuestion(aiPrompt);
            } catch (Exception e) {
                response = e.getMessage();
            }
            chatTextArea.appendText("*" + pet.getPetName() + "*\n" + response + "\n\n");
            sendButton.setDisable(false);
        };
        Thread t = new Thread(handleSend);
        t.start();

    }
}

